
import TopHeader from "@/components/header/TopHeader";
import "./globals.css";
import Header from "@/components/header/Header";
/* import { motion, AnimatePresence } from 'framer-motion'; */
import SideNav from "@/components/sidenav/SideNav";
import BannerTop from "@/components/bannerTop/BannerTop";
import locaFont from "next/font/local"
import { Lexend_Zetta } from 'next/font/google'
import Footer from "@/components/footer/Footer";
import NavDrop from "@/components/navdrop/NavDrop";

export const lexedzetta = Lexend_Zetta({
  weight: '900',
  subsets: ['latin'],

})
/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="  flex justify-center items-center flex-col bg-[#A8B4B5]   ">
        
        <div className="max-w-[1920px] w-full h-full">
        <NavDrop />
        <Header />
          {children}
          <Footer />
        </div>
        
      </body>
    </html >
  );
}